import preprocessing_raj_choksi
import decision_tree_raj_choksi
import knn_alekhya_pasupuleti
import pickle
import random_forest_mohamed_shafeeq

X_train_upsampled_LDA, X_test_upsampled_LDA_transformed, X_train_downsampled_nm_LDA, X_test_downsampled_nm_LDA_transformed, X_train_upsampled_pca, X_test_upsampled_transformed_pca, x_train_downlsampled_pca, x_test_downsampled_transformed_pca, x_train_downlsampled_pca, x_test_downsampled_transformed_pca,x_train_dres, y_train_dres, x_train_dres_nm, y_train_dres_nm, x_train_ures_SMOTE, y_train_ures_SMOTE, x_test, y_test,x_train,y_train = preprocessing_raj_choksi.raj_preprocessing()
#x_train_dres, y_train_dres, x_train_dres_nm, y_train_dres_nm, x_train_ures_SMOTE, y_train_ures_SMOTE, x_test, y_test,x_train,y_train = piyush_preprocessing.piyush_preprocessing()


print(decision_tree_raj_choksi.decisionTreeWtihSmoteUpsampledData(x_train_ures_SMOTE,y_train_ures_SMOTE,x_test,y_test))
print(decision_tree_raj_choksi.decisionTreeWithPCAandUpsampledData(X_train_upsampled_pca,y_train_ures_SMOTE,X_test_upsampled_transformed_pca,y_test))
print(decision_tree_raj_choksi.decisionTreeWithLDAandUpsampledData(X_train_upsampled_LDA,y_train_ures_SMOTE,X_test_upsampled_LDA_transformed,y_test))
print(decision_tree_raj_choksi.decisionTreeWithNearMissDownsampledData(x_train_dres_nm,y_train_dres_nm,x_test,y_test))
print(decision_tree_raj_choksi.decisionTreeWithPCAandNearMissDownsampledData(x_train_downlsampled_pca,y_train_dres_nm,x_test_downsampled_transformed_pca,y_test))
print(decision_tree_raj_choksi.decisionTreewithLDAandNearMissDownsampledData(X_train_downsampled_nm_LDA,y_train_dres_nm,X_test_downsampled_nm_LDA_transformed,y_test))
no_resampled_model = decision_tree_raj_choksi.decisionTreeWithoutResampledData(x_train,y_train,x_test,y_test)
print(decision_tree_raj_choksi.decisionTreeWithoutResamplingHyperParameterTuning(x_train,y_train,no_resampled_model))
print(decision_tree_raj_choksi.decisionTreeWithTuning(x_train,y_train,x_test,y_test))

no_resampling_model = knn_alekhya_pasupuleti.knnWithoutResampling(x_train,y_train,x_test,y_test)
print(knn_alekhya_pasupuleti.knnWithoutResamplingHyperParameterTuning(x_train,y_train,no_resampling_model))
print(knn_alekhya_pasupuleti.knnWithoutResamplingRightParameters(x_train,y_train,x_test,y_test))
print(knn_alekhya_pasupuleti.knnWithUpsampledData(x_train_ures_SMOTE,y_train_ures_SMOTE,x_test,y_test))
print(knn_alekhya_pasupuleti.knnWithNearDownsampledData(x_train_dres_nm,y_train_dres_nm,x_test,y_test))
print(knn_alekhya_pasupuleti.knnWithPCAandUpsampledData(X_train_upsampled_pca,y_train_ures_SMOTE,X_test_upsampled_transformed_pca,y_test))
print(knn_alekhya_pasupuleti.knnWWithLDAandUpsampledData(X_train_upsampled_LDA,y_train_ures_SMOTE,X_test_upsampled_LDA_transformed,y_test))
print(knn_alekhya_pasupuleti.knnWithLDAandDownsampledData(X_train_downsampled_nm_LDA,y_train_dres_nm,X_test_downsampled_nm_LDA_transformed,y_test))
print(knn_alekhya_pasupuleti.knnWithPCAandDownsampledData(x_train_downlsampled_pca,y_train_dres_nm,x_test_downsampled_transformed_pca,y_test))

print(random_forest_mohamed_shafeeq.randomForestWithSmoteUpsampledData(x_train_ures_SMOTE,y_train_ures_SMOTE,x_test,y_test))
print(random_forest_mohamed_shafeeq.randomForestPCAandUpsampledData(X_train_upsampled_pca,y_train_ures_SMOTE,X_test_upsampled_transformed_pca,y_test))
print(random_forest_mohamed_shafeeq.randomForestWithLDAUpsampledData(X_train_upsampled_LDA,y_train_ures_SMOTE,X_test_upsampled_LDA_transformed,y_test))
print(random_forest_mohamed_shafeeq.randomForestwithDownsampledData(x_train_dres_nm,y_train_dres_nm,x_test,y_test))
print(random_forest_mohamed_shafeeq.randomForestWithPCAandDownsampledData(x_train_downlsampled_pca,y_train_dres_nm,x_test_downsampled_transformed_pca,y_test,x_train_dres_nm,x_test))
print(random_forest_mohamed_shafeeq.randomForestWithLDAandDownsampledData(X_train_downsampled_nm_LDA,y_train_dres_nm,X_test_downsampled_nm_LDA_transformed,y_test))
no_resampling_model = random_forest_mohamed_shafeeq.randomForestWithoutResampling(x_train,y_train,x_test,y_test)
print(random_forest_mohamed_shafeeq.randomForestWithoutResamplingHyperparaTuning(x_train,y_train,x_test,y_test,no_resampling_model))
print(random_forest_mohamed_shafeeq.randomForestNoresamplingRightParameters(x_train,y_train,y_test,x_test))

