import preprocessing_raj_choksi
import decision_tree_raj_choksi

import pickle

X_train_upsampled_LDA, X_test_upsampled_LDA_transformed, X_train_downsampled_nm_LDA, X_test_downsampled_nm_LDA_transformed, X_train_upsampled_pca, X_test_upsampled_transformed_pca, x_train_downlsampled_pca, x_test_downsampled_transformed_pca, x_train_downlsampled_pca, x_test_downsampled_transformed_pca,x_train_dres, y_train_dres, x_train_dres_nm, y_train_dres_nm, x_train_ures_SMOTE, y_train_ures_SMOTE, x_test, y_test,x_train,y_train = preprocessing_raj_choksi.raj_preprocessing()
#x_train_dres, y_train_dres, x_train_dres_nm, y_train_dres_nm, x_train_ures_SMOTE, y_train_ures_SMOTE, x_test, y_test,x_train,y_train = piyush_preprocessing.piyush_preprocessing()


print(decision_tree_raj_choksi.decisionTreeWtihSmoteUpsampledData(x_train_ures_SMOTE,y_train_ures_SMOTE,x_test,y_test))
print(decision_tree_raj_choksi.decisionTreeWithPCAandUpsampledData(X_train_upsampled_pca,y_train_ures_SMOTE,X_test_upsampled_transformed_pca,y_test))
print(decision_tree_raj_choksi.decisionTreeWithLDAandUpsampledData(X_train_upsampled_LDA,y_train_ures_SMOTE,X_test_upsampled_LDA_transformed,y_test))
print(decision_tree_raj_choksi.decisionTreeWithNearMissDownsampledData(x_train_dres_nm,y_train_dres_nm,x_test,y_test))
print(decision_tree_raj_choksi.decisionTreeWithPCAandNearMissDownsampledData(x_train_downlsampled_pca,y_train_dres_nm,x_test_downsampled_transformed_pca,y_test))
print(decision_tree_raj_choksi.decisionTreewithLDAandNearMissDownsampledData(X_train_downsampled_nm_LDA,y_train_dres_nm,X_test_downsampled_nm_LDA_transformed,y_test))
no_resampled_model = decision_tree_raj_choksi.decisionTreeWithoutResampledData(x_train,y_train,x_test,y_test)
print(decision_tree_raj_choksi.decisionTreeWithoutResamplingHyperParameterTuning(x_train,y_train,no_resampled_model))
print(decision_tree_raj_choksi.decisionTreeWithTuning(x_train,y_train,x_test,y_test))





